name: Build NixOS Lima Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04 ubuntu-24.04-arm]
      fail-fast: false
    env:
      # HOST_ARCH value must match string in Lima download filename
      HOST_ARCH: ${{ matrix.os == 'ubuntu-24.04' && 'x86_64' || (matrix.os == 'ubuntu-24.04-arm' && 'aarch64') || 'unknown' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        env:
          # Use env variable QEMU_SYSTEM_AARCH64 to override Lima's QEMU configuration on aarch64 host
          SYSTEM_FEATURES: ${{ env.HOST_ARCH == 'aarch64' && 'kvm aarch64-linux' || 'kvm' }}
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            system-features = ${{ env.HOST_ARCH }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build aarch64 Image
        if: ${{ env.HOST_ARCH == 'aarch64' }}
        run: |
          nix build .#packages.aarch64-linux.img
          cp result/nixos.qcow2 nixos-lima-unstable-aarch64.qcow2

      - name: Build x86_64 Image
        if: ${{ env.HOST_ARCH == 'x86_64' }}
        run: |
          nix build .#packages.x86_64-linux.img
          cp result/nixos.qcow2 nixos-lima-unstable-x86_64.qcow2

      - name: Upload aarch64 image as artifact
        uses: actions/upload-artifact@v4
        if: ${{ env.HOST_ARCH == 'aarch64' }}
        with:
          name: nixos-lima-unstable-aarch64
          path: nixos-lima-unstable-aarch64.qcow2

      - name: Upload x86_64 image as artifact
        uses: actions/upload-artifact@v4
        if: ${{ env.HOST_ARCH == 'x86_64' }}
        with:
          name: nixos-lima-unstable-x86_64
          path: nixos-lima-unstable-x86_64.qcow2
