name: Build NixOS Lima Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            system-features = aarch64-linux
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          nix build .#packages.aarch64-linux.img
          cp result/nixos.img nixos-lima-unstable-aarch64.img

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-lima-unstable-aarch64
          path: nixos-lima-unstable-aarch64.img
